#ifndef GENERAL_ARRAY_CONFIG_H
#define GENERAL_ARRAY_CONFIG_H

#ifndef GEAR_DEFAULT_INIT_CAPACITY
#define GEAR_DEFAULT_INIT_CAPACITY 1
#endif

#ifndef GEAR_DEFAULT_EXPANSION
#define GEAR_DEFAULT_EXPANSION 2
#endif

#endif // GENERAL_ARRAY_CONFIG_H
